name: FreeForAll
main: com.division.freeforall.core.FreeForAll
version: 1.5.11
description: FreeForAll region system
commands:
   ffa:
      description: Defines ffa region.
      permission: freeforall.ffa
      usage: /ffa define
authors: [Mastershake71, Kwek20]
depend: [Vault]
softdepend: [Factions]